# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.3


pipelines:
  custom:
      monique_vst:
        - step:
            name: Lint, Build & Run Tests
            script:
              - apt-get update --yes
              - apt-get install --yes clang-tidy
              - make lint
              - make
              - make run_tests
